name: 'Terraform Build'

on:
  push:
    branches: [ "main" , "test"]
    paths-ignore:
      - 'helm/**'
   #   - .github/**

jobs:
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

    - name: configure env
      uses: ./.github/actions/configure_env
      with:
        aws-region: us-west-2

    - name: basic commands
      uses: ./.github/actions/test
  #      with:
  #        registry_username: ${{secrets.REGISTRY_USERNAME}}
  #        registry_password: ${{secrets.REGISTRY_PASSWORD}}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
#    - name: Terraform Init
#      run: terraform init
#
#    - name: Terraform Format
#      continue-on-error: true
#      run: terraform fmt -check
#
#    - name: Terraform Validate
#      continue-on-error: true
#      run: terraform validate -no-color
      
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      continue-on-error: true
      run: terraform plan -out "tf_plan" -input=false

    - name: Upload TF Plan
      uses: actions/upload-artifact@v2
      with:
        name: tf_plan
        path: ./tf_plan
        if-no-files-found: error
        retention-days: 1

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
  
  terraform_apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform_plan]

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
   # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Download TF Plan
      uses: actions/download-artifact@v2
      with:
        name: tf_plan
        path: ./

    - name: Terraform Apply
      run: |
        terraform show "tf_plan"
        terraform apply -input=false tf_plan 